service: coin-news

stage: prod
region: us-east-1  
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
       - lambda:InvokeFunction
      Resource: ${env:SOURCE_AS_A_SERVICE_ARN}
  usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle: 
        burstLimit: 200
        rateLimit: 100
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamic-dotenv

package:
  include:
    handler.ts

functions:
  coin-news:
    handler: handler.news
    timeout: 30

    events:
      - http:
          path: coin-news
          method: get
  
  coin-news-alert:
    handler: handler.infrequentNewsAlert
    timeout: 30

    events:
      - schedule:
          name: coin-news-alert-event
          description: 'Check for new news and send a webhook'
          rate: rate(60 minutes)
          enabled: true

  coin-news-frequent-alert:
    handler: handler.frequentNewsAlert
    timeout: 30

    events:
      - schedule:
          name: coin-news-frequent-alert-event
          description: 'Check for new news and send a webhook when it occurs frequently'
          rate: rate(3 minutes)
          enabled: true