service: aws-typescript-tests

stage: prod
region: us-east-1

provider:
  name: aws
  runtime: nodejs8.10
  usagePlan: # Optional usage plan configuration
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    handler.ts

functions:
  coin-news:
    handler: handler.news
    timeout: 30

    events:
      - http:
          path: coin-news
          method: get

